site_name: GRACC Documentation
repo_url: https://github.com/opensciencegrid/gracc
copyright: Open Science Grid

theme: readthedocs

pages:
  - 'Introduction': 'index.md'
  - User Guide:
    - Standard Interfaces: user/standard.md
    - Custom Grafana: user/grafana.md
    - Direct Queries: user/direct.md
  - Development Docs:
    - Agent Architecture: dev-docs/agent-arch.md
    - Message Queues: dev-docs/message-queues.md
    - Raw Records: dev-docs/raw-records.md
  - Operator Docs:
    - Installation: dev-docs/install-grace-db.md
    - Backup Documentation: dev-docs/backups.md
    - Operations: ops/services.md
    - Troubleshooting: ops/troubleshoot.md
  - Content Management:
    - Corrections: content/corrections.md

extra_css: 
  - css/extra.css

markdown_extensions:
  - admonition

